export const ErrorMessages = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  DISK_FULL: "DISK_FULL",
  ALREADY_EXISTS: "ALREADY_EXISTS",

  PATH_NOT_STRING: "PATH_NOT_STRING",
  PATH_EMPTY: "PATH_EMPTY",
  PATH_TOO_LONG: "PATH_TOO_LONG",
  PATH_INVALID: "PATH_INVALID",
  PATH_NO_STARTING_SLASH: "PATH_NO_STARTING_SLASH",
  PATH_NO_ENDING_SLASH: "PATH_NO_ENDING_SLASH",

  NAME_NOT_STRING: "NAME_NOT_STRING",
  NAME_EMPTY: "NAME_EMPTY",
  NAME_TOO_LONG: "NAME_TOO_LONG",
  NAME_INVALID: "NAME_INVALID",

  PATHNAME_NOT_STRING: "PATHNAME_NOT_STRING",
  PATHNAME_EMPTY: "PATHNAME_EMPTY",
  PATHNAME_TOO_LONG: "PATHNAME_TOO_LONG",
  PATHNAME_INVALID: "PATHNAME_INVALID",
  PATHNAME_NO_STARTING_SLASH: "PATHNAME_NO_STARTING_SLASH",

  NO_FOLDER: "NO_FOLDER",
  NO_FILE: "NO_FILE",

  NOT_ARRAY: "NOT_ARRAY",
  EMPTY_ARRAY: "EMPTY_ARRAY",
  ARRAY_TOO_LONG: "ARRAY_TOO_LONG",

  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  NETWORK_ERROR: "NETWORK_ERROR",
  EMPTY_BODY: "EMPTY_BODY",
};

export class AppError extends Error {
  public code: string;
  constructor(code: string) {
    super(code);
    this.code = code;
  }
}
