export const mockOptions = [
  { id: 1, name: "a" },
  { id: 1, name: "b" },
  { id: 3, name: "photo/home/pets/dogs/beagle/playing" },
  { id: 4, name: "photo/australia/wildlife/kangaroo/outback" },
  { id: 5, name: "photo/australia/wildlife/koala/eucalyptus" },
  { id: 6, name: "photo/antarctica/birds/penguins/emperor" },
  { id: 7, name: "photo///snakes/python/curled" },
  {
    id: 8,
    name: "photo/pond/reptiles/turtles/green/sunbathing/dfasdfas/dfsdfsa/dfsdfsafdf/dfsadfsaafsd",
  },
  { id: 9, name: "photo/australia/wildlife//burrow" },
  { id: 10, name: "photo/australia/wildlife/wombat/forest" },
  { id: 11, name: "photo/australia/wildlife/wombat/rocky" },
  { id: 12, name: "photo//wildlife/wombat/coastal" },
  { id: 13, name: "photo/australia/wildlife/wombat/desert" },
  { id: 14, name: "photo/australia/wildlife/wombat/snowy" },
  { id: 15, name: "photo/australia//wombat/urban" },
  { id: 16, name: "photo/australia/wildlife/wombat/cave" },
  { id: 17, name: "photo/australia/wildlife/wombat/mountain" },
  { id: 18, name: "photo//wildlife/wombat/riverbank" },
  { id: 19, name: "photo" },
  { id: 20, name: "photo/australia/wildlife/wombat/farm" },
  { id: 21, name: "photo/australia/wildlife/wombat/lake" },
  { id: 22, name: "photo/australia/wildlife/wombat/cliffside" },
  { id: 23, name: "photo/africa/mammals/lion/pride" },
  { id: 24, name: "photo/africa/mammals/elephant/herd" },
  { id: 25, name: "photo/africa/mammals/giraffe/savannah" },
  { id: 26, name: "photo/europe/birds/swans/lake" },
  { id: 27, name: "photo/europe/birds/eagle/mountain" },
  { id: 28, name: "photo/europe/cities/paris/eiffel-tower/day" },
  { id: 29, name: "photo/europe/cities/rome/colosseum/night" },
  { id: 30, name: "photo/asia/monuments/great-wall/section-3" },
  { id: 100, name: "a" },
  { id: 31, name: "photo/asia/wildlife/pandas/bamboo-forest" },
  { id: 32, name: "photo/asia/mountains/himalayas/basecamp" },
  { id: 33, name: "photo/south-america/forests/amazon/macaw" },
  { id: 34, name: "photo/south-america/forests/amazon/anaconda" },
  { id: 35, name: "photo/south-america/mountains/andes/llama" },
  { id: 36, name: "photo/antarctica/icebergs/massive" },
  { id: 37, name: "photo/north-america/national-parks/yosemite/waterfall" },
  { id: 38, name: "photo/north-america/national-parks/grand-canyon/sunset" },
  { id: 39, name: "photo/north-america/cities/new-york/skyline/night" },
  { id: 40, name: "photo/oceania/islands/fiji/beach" },
  { id: 41, name: "photo/oceania/islands/hawaii/volcano" },
  { id: 42, name: "photo/space/planets/mars/rover" },
  { id: 43, name: "photo/space/planets/jupiter/storm" },
  { id: 44, name: "photo/space/nebula/orion" },
  { id: 45, name: "photo/space/blackholes/theoretical" },
  // Odd / messy paths
  { id: 46, name: "photo///broken//slashes/test" },
  {
    id: 47,
    name: "photo/very/very/very/very/long/path/with/many/segments/to/test/truncation/in/UI",
  },
  { id: 48, name: "photo/home/pets/cats////siamese" },
  {
    id: 49,
    name: "photo/home/pets/dogs/golden-retriever/puppy/adorable/extra",
  },
  { id: 50, name: "photo/objects/vehicles/cars/tesla/model-s" },
  { id: 51, name: "photo/objects/vehicles/trains/steam-engine" },
  { id: 52, name: "photo/objects/vehicles/planes/boeing-747" },
  { id: 53, name: "photo/objects/vehicles/bikes/mountain-bike" },
  { id: 54, name: "photo/plants/trees/oak/century-old" },
  { id: 55, name: "photo/plants/flowers/rose/red" },
  { id: 56, name: "photo/plants/flowers/tulip/yellow" },
  { id: 57, name: "photo/plants/cactus/desert/spiky" },
  { id: 58, name: "photo/random/🤖/unicode/test" },
  { id: 59, name: "photo/home/decor/sofa/minimalist" },
  { id: 60, name: "photo/home/kitchen/utensils/spoon" },
  { id: 61, name: "photo/home/bathroom/mirror/round" },
  { id: 62, name: "photo/home/bedroom/bed/king-size" },
  { id: 63, name: "photo/events/wedding/beach" },
  { id: 64, name: "photo/events/birthday/children" },
  { id: 65, name: "photo/events/concert/rock-band" },
  { id: 66, name: "photo/events/festival/lanterns" },
  {
    id: 67,
    name: "photo/experimental/path_with_underscores_and_numbers_123/abc",
  },
  { id: 68, name: "photo/experimental/!@#$%^&*()/special-chars" },
  { id: 69, name: "photo//double/slash/start" },
  { id: 70, name: "photo" },
  {
    id: 70,
    name: "/root/longfolder1/longfolder2/longfolder3/longfolder4/longfolder5/longfolder6/longfolder7/longfolder8/longfolder9/longfolder10/longfolder11/longfolder12/longfolder13/longfolder14/longfolder15/longfolder16/longfolder17/longfolder18/longfolder19/longfolder20/longfolder21/longfolder22/longfolder23/longfolder24/longfolder25/longfolder26/longfolder27/longfolder28/longfolder29/longfolder30/longfolder31/longfolder32/longfolder33/longfolder34/longfolder35/longfolder36/longfolder37/longfolder38/longfolder39/longfolder40/longfolder41/longfolder42/longfolder43/longfolder44/longfolder45/longfolder46/longfolder47/longfolder48/longfolder49/longfolder50/longfolder51/longfolder52/longfolder53/longfolder54/longfolder55/longfolder56/longfolder57/longfolder58/longfolder59/longfolder60/longfolder61/longfolder62/longfolder63/longfolder64/longfolder65/longfolder66/longfolder67/longfolder68/longfolder69/longfolder70/longfolder71/longfolder72/longfolder73/longfolder74/longfolder75/longfolder76/longfolder77/longfolder78/longfolder79/longfolder80/longfolder81/longfolder82/longfolder83/longfolder84/longfolder85/longfolder86/longfolder87/longfolder88/longfolder89/longfolder90/longfolder91/longfolder92/longfolder93/longfolder94/longfolder95/longfolder96/longfolder97/longfolder98/longfolder99/longfolder100/longfolder101/longfolder102/longfolder103/longfolder104/longfolder105/longfolder106/longfolder107/longfolder108/longfolder109/longfolder110/longfolder111/longfolder112/longfolder113/longfolder114/longfolder115/longfolder116/longfolder117/longfolder118/longfolder119/longfolder120/longfolder121/longfolder122/longfolder123/longfolder124/longfolder125/longfolder126/longfolder127/longfolder128/longfolder129/longfolder130/longfolder131/longfolder132/longfolder133/longfolder134/longfolder135/longfolder136/longfolder137/longfolder138/longfolder139/longfolder140/longfolder141/longfolder142/longfolder143/longfolder144/longfolder145/longfolder146/longfolder147/longfolder148/longfolder149/longfolder150/filename.txt",
  },
];
